
services:
  producerA:
    build:
      context: ./producer_production
    image: edpo-ems-producer-production
    environment:
      JAVA_OPTS: "2022_Production2.csv"

  producerB:
    image: edpo-ems-producer-production
    environment:
      JAVA_OPTS: "2022_Production.csv"

  consumerA:
    build:
      context: ./producer_consumption
    image: edpo-ems-producer-consumption
    environment:
      JAVA_OPTS: "2022_Consumption.csv"

  consumerB:
    image: edpo-ems-producer-consumption
    environment:
      JAVA_OPTS: "2022_Consumption2.csv"

networks:
  ems:
    driver: bridge