services:
  frontend-monitoring:
    build:
      context: ./frontend-monitoring
    image: edpo-ems-frontend-monitoring
    stdin_open: true
    ports:
      - "3003:3003"
    networks:
      - ems

networks:
  ems:
    driver: bridge