spring.datasource.url: jdbc:h2:file:./camunda-h2-database

server.port: 8087

spring:
  datasource.url: jdbc:h2:file:./camunda-h2-database
  application.name: inventory
  kafka:
    bootstrap-servers: "localhost:9092"
    consumer.auto-offset-reset: earliest
    consumer:
      group-id: "ems-inventory"

zeebe:
  client:
    broker.gateway-address: "localhost:26500"
    security.plaintext: true

camunda.bpm:
  admin-user:
    id: demo
    password: demo
  filter.create: All Tasks

kafka:
  bootstrap-address: localhost:9092
  ems-payment.topic-name: ems-inventory
  group-id: "ems-inventory"
  trusted-packages: ch.unisg.ems.inventory.dto