server:
  port: 8081
  servlet:
    context-path: "/api"

spring:
  application.name: api

kafka:
  bootstrap-address: localhost:9092
  ems.topic-name: ems
  group-id: "ems"
  trusted-packages: "ch.unisg.ems.api.dto"