server:
  port: 8089
  servlet:
    context-path: "/api"

spring:
  datasource.url: jdbc:h2:file:./camunda-h2-database
  application.name: payment
  kafka:
    bootstrap-servers: "localhost:9092"
    consumer.auto-offset-reset: earliest
    consumer:
      group-id: "ems-payment"
zeebe:
  client:
    broker.gateway-address: "localhost:26500"
    security.plaintext: true

camunda.bpm:
  admin-user:
    id: demo
    password: demo
  filter.create: All Tasks

kafka:
  bootstrap-address: localhost:9092
  ems-payment.topic-name: ems-payment
  group-id: "ems-payment"
  trusted-packages: ch.unisg.ems.payment.dto
